[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy =  "autoplay '*'; display-capture '*'; document-domain '*'; encrypted-media '*'; layout-animations '*'; payment '*'; sync-xhr '*'"