[[headers]]
  for = "/*"
  [headers.values]
    accept-ranges = "bytes"
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    vary = "Cookie,User-Agent,Accept-Encoding"
    Feature-Policy = "autoplay '*'; display-capture '*'; document-domain '*'; encrypted-media '*'; layout-animations '*'; payment '*'; sync-xhr '*'"